# Generated by Django 5.1 on 2025-01-27 09:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('daily_message_limit', models.PositiveIntegerField(default=23, verbose_name='Daily Message Limit')),
                ('current_message_count', models.PositiveIntegerField(default=0, verbose_name='Current Message Count')),
                ('token_limit', models.PositiveIntegerField(default=300, help_text='Maximum tokens for the response. Must be between 300 and 1000.', verbose_name='Token Output Limit')),
                ('assistant_role', models.CharField(choices=[('general_physician', 'پزشک عمومی'), ('surgeon', 'جراح'), ('psychologist', 'روانشناس'), ('psychiatrist', 'روانپزشک'), ('pain_specialist', 'متخصص درد'), ('cardiologist', 'متخصص قلب'), ('neurologist', 'متخصص مغز و اعصاب'), ('endocrinologist', 'متخصص غدد'), ('pediatrician', 'متخصص اطفال'), ('dermatologist', 'متخصص پوست'), ('orthopedic', 'متخصص ارتوپدی')], default='general_physician', max_length=50, verbose_name='Assistant Role')),
                ('system_role', models.CharField(choices=[('therapeutic', 'سیستم درمانی'), ('diagnostic', 'سیستم تشخیصی'), ('triage', 'سیستم تریاژ'), ('predictive', 'سیستم پیش\u200cبینی'), ('educational', 'سیستم آموزشی'), ('research', 'سیستم پژوهشی')], default='therapeutic', max_length=50, verbose_name='System Role')),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(help_text='Message sent by the user.', verbose_name='User Message')),
                ('bot_response', models.TextField(help_text='Response sent by the bot.', verbose_name='Bot Response')),
                ('assistant_role', models.CharField(help_text='Role of the assistant during this session.', max_length=50, verbose_name='Assistant Role')),
                ('system_role', models.CharField(help_text='Role of the system during this session.', max_length=50, verbose_name='System Role')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='auth_bot.baleuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
